services:
  # db:
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: 665809
  #     MYSQL_USER: 665809
  #     MYSQL_PASSWORD: 665809
  #   volumes:
  #     - data:/var/lib/mysql
  #   ports:
  #     - 3307:3307
  #   healthcheck:
  #     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  # phpmyadmin:
  #   image: phpmyadmin:5.2.2-fpm-alpine
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - 8080:80
  app:
    build: .
    environment:
      - DB_HOST=172.17.51.94
      - DB_USER=665809
      - DB_PASSWORD=665809
      - DB_NAME=665809
      - DB_PORT=3307
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    user: "${UID:-1}:${GID:-1}"
volumes:
  data: